### ISSUE TITLE
Question: Can I apply more circles on the same element, connected to each other in a kind of chain?

### ISSUE THREAD

**Issue by p4535992** [tigrr/circle-progress#13]
Can I apply more circles on the same element, connected to each other in a kind of chain?

I currently have two circles:
Circle X (outermost circle): 100/100
Circle Y (inner circle): 30/30

and I would like that by decrementing the total value 130 you would see circle Y decrease and when you reached 0 see the value on circle X decrease.

**Comment by tigrr** [comment]
You can layer two Circle Progresses one on top of the other. See [this demo on jsfiddle](https://jsfiddle.net/tikosar/9xv2t8cs/).
Note that you will have to increase the stroke width and font size of the inner circle so that it matches those of the bigger outer circle.

**Comment by p4535992** [comment]
Wow ty for the fast response!
