### ISSUE TITLE
How can I show the value and max number as currency?

### ISSUE THREAD

**Issue by MFahadP** [tigrr/circle-progress#16]
Hi, how can I show the numbers as currency with commas and a currency symbol?

**Comment by tigrr** [comment]
Hi, sorry for late reply.

You can use the function form of the `textFormat` property together with the Intl Number's API:

```js
// First, define our formatter
const formatter = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })

// Then use it in Circle Progress
const cp = new CircleProgress('.progress', {
	value: 0,
	max: 100,
	textFormat: (value) => formatter.format(value),
})
```

See complete demo on [JS Fiddle](https://jsfiddle.net/tikosar/hLfbt1z0/)

To learn more about Intl API, see [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat)

**Comment by tigrr** [comment]
If that answers your question, I will close this issue.
