### ISSUE TITLE
Method to replay the animation

### ISSUE THREAD

**Issue by thanhquocuit** [tigrr/circle-progress#17]
Hi there,

I saw you do replay the animation on the example page but didn't know how to do it. Could you please show me the function to call or methods to manually trigger the animation anytime I want?

Thank you.

**Comment by NordinGit** [comment]
I was looking for the same thing.

**Comment by tigrr** [comment]
The animation is played automatically every time value changes. To play the animation from value *a* to value *b* you would have to follow this steps:
1. Set animation to `'none'` (unless you want the circle progress to animate to *a* too);
2. Set the value to *a*;
3. Set animation back to whatever easing function you want;
4. Set the value to *b*.

For more details on the example and landing pages, you can check the [docs](https://github.com/tigrr/circle-progress/tree/master/docs) directory of this repo.

**Comment by tigrr** [comment]
@thanhquocuit , @NordinGit , if the description above is sufficient and you won't have additional questions, I will close this issue.
