### ISSUE TITLE
Hi I have some question about circle-progress.

### ISSUE THREAD

**Issue by legion7298** [tigrr/circle-progress#18]
I want to show progress text like minute : second via circle-progress.
Could you please teach me "What do I have to do?"

**Comment by tigrr** [comment]
You can use the function form of the `textFormat` property.
Something like this:

```js
const cp = new CircleProgress('.progress', {
	value: 0,
	max: 3600, // 3600 seconds = 1 hour
	textFormat: (value) => {
		const min = String(Math.floor(value / 60)).padStart(2, '0')
		const sec = String(value - min * 60).padStart(2, '0')
		return `${min}:${sec}`
	},
})
```

See [complete demo on jsFiddle](https://jsfiddle.net/tikosar/4dyq2ts6/)

Please, check [the list of options](https://github.com/tigrr/circle-progress#all-available-options) for details, the [examples](https://tigrr.github.io/circle-progress/examples.html) for some inspiration and [questions in the issues](https://github.com/tigrr/circle-progress/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion) for similar questions.

**Comment by tigrr** [comment]
If that answers your question, I will close this issue. Please, feel free to reopen it if you have further inquiries on the topic.
