### ISSUE TITLE
Additional text below the value

### ISSUE THREAD

**Issue by ScanThemes** [tigrr/circle-progress#2]
Is it possible to add additional text under the value?
For instance:
<img src="https://i.imgur.com/DqvdIZB.png">

Thanks.

**Comment by tigrr** [comment]
You can generate arbitrary SVG code passing your function as the value of `textFormat` option.

See [this fiddle](https://jsfiddle.net/tikosar/ctozxfp0/).

**Be careful** though. `innerHTML` is used to insert the result of function call. All dynamics values must be escaped. (No need to escape `value` and `max` arguments to custom function, they are already formatted as numbers.)

**Comment by tigrr** [comment]
@ScanThemes one more thing. I've just updated the repo. Please make sure to use the latest version.

**Comment by ScanThemes** [comment]
@tigrr Excellent, thank you!
