### ISSUE TITLE
Specifying Properties When Importing from CDN

### ISSUE THREAD

**Issue by emmavray** [tigrr/circle-progress#21]
I'm linking this library from the CDN in a static html page, which is packaged as a standalone html document with no dependencies. I'm using the CDN example from the README:

```
<script src="https://cdn.jsdelivr.net/npm/js-circle-progress/dist/circle-progress.min.js" type="module"></script>

<circle-progress value="50" max="100"></circle-progress>
```

I'd like to specify some properties (such as textFormat) using html attributes:
`<circle-progress textFormat="value" value="50" max="100"></circle-progress>`

This doesn't work. The problem may be obvious to frontend developers (which I am not) but I'm unsure how this should work in an environment when I cannot import a node module or a local js file.

Is what I'm trying to do even possible, or are these attributes only available via the constructor when creating the object in js?

**Comment by tigrr** [comment]
When setting attributes (not properties) you have to keep in mind that some attribute names are different than the corresponding property names. Property names are _camelCased_, whereas attribute names are _kebab-cased_. In your case, the `textFormat` property is set as `text-format` attribute. So the complete HTML would be:
```html
<circle-progress text-format="value" value="50" max="100"></circle-progress>
```
I updated the docs to reflect that. You can now see the attribute name corresponding to each property in [the properties table](https://github.com/tigrr/circle-progress#all-available-properties).

**Comment by emmavray** [comment]
thanks for the quick response -- I suspected it would be something simple!
