### ISSUE TITLE
anticlockwise don't work!

### ISSUE THREAD

**Issue by brood09** [tigrr/circle-progress#22]
Hi, @tigrr 
I'm trying to make one circle progress, everything is ok, but I need it to go anti-clockwise,  I'm set the parametr *anticlockwise: true* and don't work, I'm trying set *anticlockwise: false* and likewise nothing works. No matter what I set to the parameter, it goes clockwise. Thx.

My Code: 
`
new CircleProgress('.progress-circular', {
	min: 0,
	max: 100,
	value: 100,
	startAngle: 0,
	anticlockwise: true,
	textFormat: 'none',
	animationDuration: 5500,
	animation: 'linear',
});
`

**Comment by tigrr** [comment]
Hi. Which version are you using?

**Comment by tigrr** [comment]
@brood09 ?

**Comment by tigrr** [comment]
Closing due to lack of feedback from the OP.
