### ISSUE TITLE
text-format=“percent” prop not working

### ISSUE THREAD

**Issue by younochGain** [tigrr/circle-progress#23]
I am using js-circle-progress component in my Vue 2 project and I want to show the progress value as a percentage inside the circle. I tried to use the text-format=“percent” prop as shown in the documentation, but it does not work. The text inside the circle shows the raw value instead of the percentage.

```
<circle-progress :value="80" :size="200" :stroke-width="10" :stroke-color="#00ff00" text-format="percent" />
```

version name: "js-circle-progress": "^1.0.0-beta.0",

**Comment by tigrr** [comment]
I am not familiar with Vue, so I am not sure I can help. But let's try.
Can you please share a JSFiddle or CodePen demo?

**Comment by tigrr** [comment]
Closing due to lack of feedback from the OP.
