### ISSUE TITLE
Changes not working in html

### ISSUE THREAD

**Issue by KaviHarjani** [tigrr/circle-progress#24]
Hello tigrr,

Thank you for the great library, it's truly awesome, 

However I am unable to use it in html could you please help me out?
I am using html, css and vanilla javascript

<script src="https://cdn.jsdelivr.net/npm/js-circle-progress/dist/circle-progress.min.js" type="module"></script>

<circle-progress value="50" max="100" textFormat="percent"></circle-progress>

It doesn't change the text format to percentage,

Or take the css, 

I want to apply this css

`.circle-progress-value {
	stroke-width: 6px;
	stroke: white;
	stroke-linecap: round;
}
.circle-progress-circle {
	stroke-width: 8px;
	stroke: #888;
}
.circle-progress-text {
	fill: #888;
}`

You can find my fiddle here
https://codepen.io/kaviharjani/pen/VwgYroZ

Thank you

**Comment by tigrr** [comment]
Hello, Kavi,

Thank you for your kind words.

Some attribute names are different than the corresponding property names. Property names are _camelCased_, whereas attribute names are _kebab-cased_. If text format is set as a JavaScript property, it is `textFormat`; and if it is set as an HTML attribute, `text-format` should be used instead. Please, refer to [the properties / attributes table](https://github.com/tigrr/circle-progress#all-available-properties) for the property and attribute names.

For CSS you have to use [_parts_](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) like so: `circle-progress::part(value) { ... }`. See the [Styling section](https://github.com/tigrr/circle-progress#styling) in the docs.
