### ISSUE TITLE
rerender svg

### ISSUE THREAD

**Issue by PanWcislo** [tigrr/circle-progress#27]
I am trying to create a countdown component for GrapesJS but when changing the date everything resets and the svg is deleted. It does not render it again. I guess calling (new CircleProgress ) again on the same element doesn't work? How can I fix this?

**Comment by tigrr** [comment]
Which Circle Progress version are you using?

**Comment by PanWcislo** [comment]
I changed to the latest 1.0.0 works better but not quite right
![image](https://github.com/tigrr/circle-progress/assets/43911788/2844f878-779e-4193-998d-b362a4ce0cb6)

**Comment by tigrr** [comment]
Please, share your code. If you can create a demo on Codepen.io or jsfiddle.net or something else, would be even better.
