### ISSUE TITLE
Number of Segments in Circle

### ISSUE THREAD

**Issue by emorling** [tigrr/circle-progress#28]
Awesome library!

is it possible to define the number of segments in the circle?

For example:

min: 0
max: 10
value: 5

To have 10 segments that make up the circle, and 5 of them "filled".

**Comment by tigrr** [comment]
Thank you!

If I understand you correctly, what you need is something like these:

![Screenshot_20240128_220654_Chrome](https://github.com/tigrr/circle-progress/assets/7148327/8476a3f1-77b4-42e0-841a-d8c6f02ef846)
![Screenshot_20240128_220629_Chrome](https://github.com/tigrr/circle-progress/assets/7148327/42d41d42-025e-4291-97e9-b681ec2e9f18)
![Screenshot_20240128_220603_Chrome](https://github.com/tigrr/circle-progress/assets/7148327/84e61e6f-458c-4ff4-98f8-1b2487ee4b6a)
![Screenshot_20240128_220738_Chrome](https://github.com/tigrr/circle-progress/assets/7148327/2c42d799-d611-4669-af71-9fab585e3788)



You can customize Circle Progress's look with CSS. 

Please, check these and other examples along with their code on the [examples page](https://tigrr.github.io/circle-progress/examples.html).

**Comment by tigrr** [comment]
@emorling did that answer your question?
