### ISSUE TITLE
Updating startAngle is not animated

### ISSUE THREAD

**Issue by noel-schenk** [tigrr/circle-progress#3]
If you're updating the startAngle it's not animated like the value, min and max.

https://jsfiddle.net/s5gbj0dn/

This is a really awesome library, thank you for building it!

**Comment by tigrr** [comment]
Thank you!
My expected usage scenario was specifying the `startAngle` just once at the initiation, so I didn't foresee that updating the angle in the process would be necessary.
Could you please share your use-case in a little detail?

**Comment by noel-schenk** [comment]
hey @tigrr sure I'm trying to display the position of a steering wheel.
I have s short example here: https://codepen.io/noelelias/pen/wvKOdQy

**Comment by tigrr** [comment]
@noelelias I didn't quite get why you would want to present a steering wheel as a progressbar. But anyway, if you don't need to have text inside CircleProgress, you can easily accomplish the task the way you do in the pen: by animating `transform: rotate`.
