### ISSUE TITLE
Reverse percentage ?

### ISSUE THREAD

**Issue by florent-p** [tigrr/circle-progress#30]
Hi !

Is there any possibility to use the gauge with a "reverse percentage" ?
I have a statistic set that I aim to get the lowest possible. For exemple :

Current number (value) : 968
Objective : 606
So the objective is not fully fullfilled (it's 63% fullfilled), I'm trying to make it under 606. .

I can't get to make the gauge work this way.
I tried to set "value" to the current number, "min" to "606" and "max" to "0" but the gauge fill entirely.

Maybe I'm getting this wrong.
Can you help me with this ?

Thank you very much :)

**Comment by tigrr** [comment]
I don't entirely understand your needs. Could you maybe share some sketches how you want the progress to look at the start, at the end and in between?

**Comment by florent-p** [comment]
Hi, thank you for answering so fast.
I'll try to make myself clearer.

Generally speaking, gauges you provide are used to show statistics (or else) that go from a number (min) to a higher number (max), and the "value" is used to display a percentage that go up as the value goes **up**.

I have a case that would need this process to be "reversed" : the percentage should go up as the value goes **down**.
We need to show the statistics of absenteeism, so the lowest the value is, the better and the closest to our goal (100%).

We still have a "min" and a "max" numbers : 
- "min" would be 100, for instance (0%)
- "max" would be 30, the goal we need to achieve (100%)
- anything **under** 30 would give a percentage above 100%

![gauge](https://github.com/tigrr/circle-progress/assets/26672853/1bb9e8c2-d25b-405a-a28b-1362040ad486)

I hope this is clear enough, otherwise I'll give you another example :)
Thank you very much !

**Comment by tigrr** [comment]
I don't understand why don't you just pass 0% to 100% to the widget and do the translation yourself.

**Comment by tigrr** [comment]
If you need custom text for the textual representation of the current value, you can pass a callback function as `format`.

**Comment by tigrr** [comment]
Please, let me know if you need any additional assistance.
