### ISSUE TITLE
Changing the color according the value (newVersion)

### ISSUE THREAD

**Issue by mcsahmaran** [tigrr/circle-progress#31]
Hi,

first of all thanks a lot for this circle animation. It is really great.
I was trying to change the color of the circle according the value. 
I saw there  was already a request/question regarding this issue, but
the solution you gave was for the old version.

Could you please provide me a solution, so I can change the color
according the progress of the circle. Where do I have to  make any 
changes?

Thanks a lot in advance.
mcsahmaran

**Comment by tigrr** [comment]
Hi,
The solution is, as you mentioned, the same as before, with the only difference being the CSS selector: now it's `circle-progress::part(value)`. You can style the `stroke` CSS property.

**Comment by mcsahmaran** [comment]
Thanks for the answer. I got it working now.
