### ISSUE TITLE
Disable built-in styling

### ISSUE THREAD

**Issue by kulbabskyy** [tigrr/circle-progress#37]
Hello Tigran.

I want to ask if its possible to disable the default progress styling, that is added in the shadow#root in the <style> tag before the SVG.
For example i have created own fallback with the CSS variables, so i basically dont need a default one.

How do you think its possible to do optionally?

Kind Regards,
Anatoliy

**Comment by tigrr** [comment]
Hi, Anatoliy,

Why do you want the default styles disabled? Did you know that you can overwrite them in your CSS?

**Comment by kulbabskyy** [comment]
Sure, that what I've done by adding own default, variable-based styling of each svg part to inherit website theme style, and by this reason I asked if it's possible to remove an default style tag since it will never be used.

This is like to start with a clean layout without overrides.

**Comment by tigrr** [comment]
There is no way to remove the default styling. You can only override it.

The defaults are minimal styles, so, if you were to use your own styling, you would provide those styles anyway, no additional measure is taken for "resetting" the defauls.

**Comment by kulbabskyy** [comment]
OK, no problem, Thank you for the reply.
