### ISSUE TITLE
set custom text format for <circle-progress> initialized via attributes?

### ISSUE THREAD

**Issue by kulbabskyy** [tigrr/circle-progress#39]
Hi Tigran, it is posible to set custom text format for `<circle-progress>` nodes that is initialized via attributes?

```
<script src="https://cdn.jsdelivr.net/npm/js-circle-progress/dist/circle-progress.min.js" type="module"></script>
<circle-progress id="my-id" value="50" max="100" text-format=""></circle-progress>
```

My main goal is to use `Intl.NumberFormat` like in this [example](https://jsfiddle.net/tikosar/hLfbt1z0/) you have posted.

Thank you!

**Comment by tigrr** [comment]
Hi, Anatoliy, 

Custom text format is provided via a function, and it is not possible in HTML to set attributes other than string or boolean. You will have to use the `textFormat` property on the Element.
