### ISSUE TITLE
进度条在走的时候，中间的数字怎么设置会有效果

### ISSUE THREAD

**Issue by jiekoyue** [tigrr/circle-progress#4]
进度条在走的时候，显示的数字是从0跟随进度条慢慢加到设置的数值

**Comment by tigrr** [comment]
Unfortunately I don't understand Chinese, and Google Translate doesn't translate your sentence in a comprehensible way. Please, describe your issue in English if you can. Maybe you could provide a demo code, screenshot or video screen capture?

**Comment by tigrr** [comment]
@jiekoyue, please respond with some details in English or Russian if you can. Otherwise I'll consider this issue closed.

**Comment by tigrr** [comment]
Closing due to no response from the reporter.
